AWSTemplateFormatVersion: '2010-09-09'
Description: |
  IAM Role for BYOC Platform deployment.
  This role allows the BYOC platform to provision infrastructure in your AWS account.
  
  Deploy this template in your AWS account and provide the Role ARN to the platform.

Parameters:
  TrustedAccountId:
    Type: String
    Description: The AWS account ID of the BYOC platform provider
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be a valid 12-digit AWS account ID

  ExternalId:
    Type: String
    Description: External ID for secure role assumption (provided by the platform)
    MinLength: 10
    MaxLength: 128
    AllowedPattern: '^[a-zA-Z0-9-_]+$'
    ConstraintDescription: Must be alphanumeric with hyphens and underscores

  RoleName:
    Type: String
    Default: BYOCPlatformDeployRole
    Description: Name for the IAM role
    AllowedPattern: '^[a-zA-Z0-9+=,.@_-]+$'
    MaxLength: 64

Resources:
  # IAM Role that the BYOC platform assumes
  BYOCDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Description: Role for BYOC platform to deploy infrastructure
      MaxSessionDuration: 14400  # 4 hours for long deployments
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${TrustedAccountId}:root'
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId
      Tags:
        - Key: ManagedBy
          Value: BYOCPlatform
        - Key: Purpose
          Value: InfrastructureDeployment

  # Policy for VPC and networking
  NetworkingPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BYOCNetworkingPolicy
      Roles:
        - !Ref BYOCDeployRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: VPCManagement
            Effect: Allow
            Action:
              - ec2:CreateVpc
              - ec2:DeleteVpc
              - ec2:DescribeVpcs
              - ec2:ModifyVpcAttribute
              - ec2:CreateSubnet
              - ec2:DeleteSubnet
              - ec2:DescribeSubnets
              - ec2:ModifySubnetAttribute
              - ec2:CreateInternetGateway
              - ec2:DeleteInternetGateway
              - ec2:AttachInternetGateway
              - ec2:DetachInternetGateway
              - ec2:DescribeInternetGateways
              - ec2:CreateNatGateway
              - ec2:DeleteNatGateway
              - ec2:DescribeNatGateways
              - ec2:AllocateAddress
              - ec2:ReleaseAddress
              - ec2:DescribeAddresses
              - ec2:AssociateAddress
              - ec2:DisassociateAddress
              - ec2:CreateRouteTable
              - ec2:DeleteRouteTable
              - ec2:DescribeRouteTables
              - ec2:CreateRoute
              - ec2:DeleteRoute
              - ec2:ReplaceRoute
              - ec2:AssociateRouteTable
              - ec2:DisassociateRouteTable
              - ec2:CreateSecurityGroup
              - ec2:DeleteSecurityGroup
              - ec2:DescribeSecurityGroups
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:AuthorizeSecurityGroupEgress
              - ec2:RevokeSecurityGroupIngress
              - ec2:RevokeSecurityGroupEgress
              - ec2:CreateTags
              - ec2:DeleteTags
              - ec2:DescribeTags
              - ec2:DescribeAvailabilityZones
              - ec2:DescribeAccountAttributes
            Resource: '*'

  # Policy for EKS cluster management
  EKSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BYOCEKSPolicy
      Roles:
        - !Ref BYOCDeployRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EKSClusterManagement
            Effect: Allow
            Action:
              - eks:CreateCluster
              - eks:DeleteCluster
              - eks:DescribeCluster
              - eks:UpdateClusterConfig
              - eks:UpdateClusterVersion
              - eks:ListClusters
              - eks:TagResource
              - eks:UntagResource
              - eks:CreateNodegroup
              - eks:DeleteNodegroup
              - eks:DescribeNodegroup
              - eks:UpdateNodegroupConfig
              - eks:UpdateNodegroupVersion
              - eks:ListNodegroups
              - eks:CreateAddon
              - eks:DeleteAddon
              - eks:DescribeAddon
              - eks:UpdateAddon
              - eks:ListAddons
              - eks:DescribeAddonVersions
              - eks:AssociateIdentityProviderConfig
              - eks:DisassociateIdentityProviderConfig
              - eks:DescribeIdentityProviderConfig
              - eks:ListIdentityProviderConfigs
              - eks:CreateAccessEntry
              - eks:DeleteAccessEntry
              - eks:DescribeAccessEntry
              - eks:ListAccessEntries
              - eks:AssociateAccessPolicy
              - eks:DisassociateAccessPolicy
              - eks:ListAccessPolicies
            Resource: '*'

  # Policy for IAM role management (for EKS, Karpenter, IRSA)
  IAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BYOCIAMPolicy
      Roles:
        - !Ref BYOCDeployRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: IAMRoleManagement
            Effect: Allow
            Action:
              - iam:CreateRole
              - iam:DeleteRole
              - iam:GetRole
              - iam:UpdateRole
              - iam:ListRoles
              - iam:TagRole
              - iam:UntagRole
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:GetRolePolicy
              - iam:ListRolePolicies
              - iam:ListAttachedRolePolicies
              - iam:CreatePolicy
              - iam:DeletePolicy
              - iam:GetPolicy
              - iam:GetPolicyVersion
              - iam:ListPolicies
              - iam:ListPolicyVersions
              - iam:CreatePolicyVersion
              - iam:DeletePolicyVersion
              - iam:TagPolicy
              - iam:UntagPolicy
              - iam:CreateInstanceProfile
              - iam:DeleteInstanceProfile
              - iam:GetInstanceProfile
              - iam:AddRoleToInstanceProfile
              - iam:RemoveRoleFromInstanceProfile
              - iam:ListInstanceProfiles
              - iam:ListInstanceProfilesForRole
              - iam:TagInstanceProfile
              - iam:UntagInstanceProfile
              - iam:PassRole
              - iam:CreateOpenIDConnectProvider
              - iam:DeleteOpenIDConnectProvider
              - iam:GetOpenIDConnectProvider
              - iam:TagOpenIDConnectProvider
              - iam:UntagOpenIDConnectProvider
              - iam:UpdateOpenIDConnectProviderThumbprint
              - iam:AddClientIDToOpenIDConnectProvider
              - iam:RemoveClientIDFromOpenIDConnectProvider
              - iam:ListOpenIDConnectProviders
              - iam:CreateServiceLinkedRole
            Resource: '*'

  # Policy for EC2 (Karpenter node provisioning)
  EC2Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BYOCEC2Policy
      Roles:
        - !Ref BYOCDeployRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EC2InstanceManagement
            Effect: Allow
            Action:
              - ec2:RunInstances
              - ec2:TerminateInstances
              - ec2:DescribeInstances
              - ec2:DescribeInstanceTypes
              - ec2:DescribeInstanceTypeOfferings
              - ec2:DescribeImages
              - ec2:DescribeLaunchTemplates
              - ec2:DescribeLaunchTemplateVersions
              - ec2:CreateLaunchTemplate
              - ec2:CreateLaunchTemplateVersion
              - ec2:DeleteLaunchTemplate
              - ec2:DeleteLaunchTemplateVersions
              - ec2:ModifyLaunchTemplate
              - ec2:CreateFleet
              - ec2:DeleteFleets
              - ec2:DescribeFleets
              - ec2:DescribeFleetHistory
              - ec2:DescribeFleetInstances
              - ec2:DescribeSpotPriceHistory
              - ec2:DescribeVolumes
              - ec2:CreateVolume
              - ec2:DeleteVolume
              - ec2:AttachVolume
              - ec2:DetachVolume
              - ec2:ModifyVolume
            Resource: '*'
          - Sid: SSMParameterAccess
            Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
            Resource:
              - !Sub 'arn:aws:ssm:*:${AWS::AccountId}:parameter/aws/*'
              - 'arn:aws:ssm:*::parameter/aws/*'

  # Policy for Load Balancers
  ELBPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BYOCELBPolicy
      Roles:
        - !Ref BYOCDeployRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: LoadBalancerManagement
            Effect: Allow
            Action:
              - elasticloadbalancing:CreateLoadBalancer
              - elasticloadbalancing:DeleteLoadBalancer
              - elasticloadbalancing:DescribeLoadBalancers
              - elasticloadbalancing:ModifyLoadBalancerAttributes
              - elasticloadbalancing:DescribeLoadBalancerAttributes
              - elasticloadbalancing:CreateTargetGroup
              - elasticloadbalancing:DeleteTargetGroup
              - elasticloadbalancing:DescribeTargetGroups
              - elasticloadbalancing:ModifyTargetGroup
              - elasticloadbalancing:ModifyTargetGroupAttributes
              - elasticloadbalancing:DescribeTargetGroupAttributes
              - elasticloadbalancing:RegisterTargets
              - elasticloadbalancing:DeregisterTargets
              - elasticloadbalancing:DescribeTargetHealth
              - elasticloadbalancing:CreateListener
              - elasticloadbalancing:DeleteListener
              - elasticloadbalancing:DescribeListeners
              - elasticloadbalancing:ModifyListener
              - elasticloadbalancing:CreateRule
              - elasticloadbalancing:DeleteRule
              - elasticloadbalancing:DescribeRules
              - elasticloadbalancing:ModifyRule
              - elasticloadbalancing:AddTags
              - elasticloadbalancing:RemoveTags
              - elasticloadbalancing:DescribeTags
              - elasticloadbalancing:SetSecurityGroups
              - elasticloadbalancing:SetSubnets
            Resource: '*'

  # Policy for CloudWatch Logs (EKS logging)
  CloudWatchPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BYOCCloudWatchPolicy
      Roles:
        - !Ref BYOCDeployRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CloudWatchLogsManagement
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:DeleteLogGroup
              - logs:DescribeLogGroups
              - logs:PutRetentionPolicy
              - logs:DeleteRetentionPolicy
              - logs:TagLogGroup
              - logs:UntagLogGroup
              - logs:ListTagsLogGroup
            Resource: '*'

  # Policy for KMS (encryption)
  KMSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BYOCKMSPolicy
      Roles:
        - !Ref BYOCDeployRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: KMSKeyManagement
            Effect: Allow
            Action:
              - kms:CreateKey
              - kms:DescribeKey
              - kms:GetKeyPolicy
              - kms:GetKeyRotationStatus
              - kms:ListKeys
              - kms:ListAliases
              - kms:CreateAlias
              - kms:DeleteAlias
              - kms:UpdateAlias
              - kms:TagResource
              - kms:UntagResource
              - kms:ListResourceTags
              - kms:EnableKeyRotation
              - kms:DisableKeyRotation
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
              - kms:Encrypt
              - kms:Decrypt
              - kms:GenerateDataKey
              - kms:GenerateDataKeyWithoutPlaintext
            Resource: '*'

  # Policy for pricing API (Karpenter)
  PricingPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BYOCPricingPolicy
      Roles:
        - !Ref BYOCDeployRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PricingAccess
            Effect: Allow
            Action:
              - pricing:GetProducts
              - pricing:DescribeServices
              - pricing:GetAttributeValues
            Resource: '*'

  # Policy for STS (for OIDC/IRSA)
  STSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BYOCSTSPolicy
      Roles:
        - !Ref BYOCDeployRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: STSAccess
            Effect: Allow
            Action:
              - sts:GetCallerIdentity
              - sts:AssumeRole
              - sts:AssumeRoleWithWebIdentity
            Resource: '*'

Outputs:
  RoleArn:
    Description: ARN of the IAM role for BYOC platform
    Value: !GetAtt BYOCDeployRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'

  RoleName:
    Description: Name of the IAM role
    Value: !Ref BYOCDeployRole

  ExternalId:
    Description: External ID used for role assumption (keep this secure)
    Value: !Ref ExternalId

  TrustedAccountId:
    Description: AWS account ID trusted to assume this role
    Value: !Ref TrustedAccountId

  DeployCommand:
    Description: AWS CLI command to deploy this template
    Value: !Sub |
      aws cloudformation create-stack \
        --stack-name byoc-platform-role \
        --template-body file://customer-iam-role.yaml \
        --parameters \
          ParameterKey=TrustedAccountId,ParameterValue=<PLATFORM_ACCOUNT_ID> \
          ParameterKey=ExternalId,ParameterValue=<YOUR_EXTERNAL_ID> \
        --capabilities CAPABILITY_NAMED_IAM
